# Generated by Django 4.2.2 on 2023-07-31 12:58

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='is_audio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='chat_type',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('GROUP', 'Group'), ('CHANNEL', 'Channel')], default=chat.models.ChatType['PRIVATE'], max_length=7),
        ),
    ]
