# Generated by Django 4.2.2 on 2023-07-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_file_is_audio_alter_chatroom_chat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
