# Generated by Django 4.2.2 on 2023-07-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatmessage_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
    ]
