# Generated by Django 4.2.2 on 2023-07-25 13:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_role_privileges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='privileges',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Resident Privilege', 'Привилегия Резидента'), ('ALLOW_EVENT_CREATE', 'Привилегия на создание мероприятия'), ('ALLOW_EVENT_UPDATE', 'Привилегия на обновление данных мероприятия'), ('ALLOW_EVENT_DELETE', 'Привилегия на удаление мероприятия'), ('ALLOW_NEWS_CREATE', 'Привилегия на создание новости'), ('ALLOW_NEWS_UPDATE', 'Привилегия на обновление данных новости'), ('ALLOW_NEWS_DELETE', 'Привилегия на удаление новости'), ('ALLOW_REQUEST_CREATE', 'Привилегия на создание запроса'), ('ALLOW_REQUEST_UPDATE', 'Привилегия на обновление данных запроса'), ('ALLOW_REQUEST_DELETE', 'Привилегия на удаление запроса'), ('ALLOW_REQUEST_FROM_ALL_RESIDENT_READ', 'Привилегия на просмотр всех запросов'), ('ALLOW_REQUEST_WRITE_RESPONSE', 'Привилегия на написание ответа запросу'), ('ALLOW_RESIDENT_BOOKED_READ', 'Привилегия на просмотр, забранированных на мероприятие, резидентов'), ('ALLOW_RESIDENT_BOOKING', 'Привилегия на удовлетворение брони резидента'), ('ALLOW_VOTE_CREATE', 'Привилегия на создание голосования'), ('ALLOW_RESIDENT_UPDATE', 'Привилегия на обновление данных резидента'), ('ALLOW_CHAT_CREATE', 'Привилегия на создание чата'), ('ALLOW_CHAT_UPDATE', 'Привилегия на обновление данных чата')], max_length=100), blank=True, default=list, size=None, verbose_name='Привилегии'),
        ),
    ]
